---
env:
  name: PathFollower-v0
  path: /home/niklaspaulig/Dropbox/TU Dresden/TUD_RL/tud_rl/envs/_envs/PathFollower.py
  max_episode_steps: 800
  state_type: feature
  wrappers: []
  wrapper_kwargs: {}
  env_kwargs:
    epi_steps: 800
    direction: 1
    mode: step
  info: validate
agent:
  DQN: {}
  DDQN: {}
  SCDQN_a:
    sc_beta: 2
  SCDQN_b:
    sc_beta: 3
  SCDQN_c:
    sc_beta: 4
  ACCDDQN_a:
    AC_K: 2
  BootDQN:
    K: 10
    mask_p: 1
    grad_rescale: true
  EnsembleDQN:
    N: 5
    N_to_update: 1
  MaxMinDQN_a:
    N: 3
    N_to_update: 1
  MaxMinDQN_b:
    N: 5
    N_to_update: 
  KEBootDQN:
    double:
    kernel: gaussian_cdf
    kernel_param: 1
    K: 10
    mask_p: 1
    grad_rescale: true
  ComboDQN: {}
img_height: 120
img_width: 120
seed: 4484
timesteps: 1000
epoch_length: 5000
eval_episodes: 1
dqn_weights:
input_norm: false
input_norm_prior:
gamma: 0.99
eps_init: 1
eps_final: 0.01
eps_decay_steps: 1_000_000
tgt_update_freq: 1000
net_struc:
  - - 256
    - relu
  - - 128
    - relu
  - identity
optimizer: Adam
loss: MSELoss
lr: 0.00005
lr_final:
lr_decay_steps:
buffer_length: 1_000_000
grad_rescale: false
grad_clip: false
act_start_step: 1000
upd_start_step: 1000
upd_every: 1
batch_size: 128
device: cuda
output_dir:
